implemented animalUtil class
Timothy-Toombs/AnimalTracker pull request #5
Opened 2020-09-24 01:30 UTC by Kutaho

2020-09-27 06:27 UTC, Timothy-Toombs requested changes

2020-09-27 06:27 UTC, Timothy-Toombs commented on AnimalTracker/app/src/main/java/toombs/animaltracker/DummyPage.java
> +            Animal A = new Animal("Dingus", "N/A", "Zeus", new GregorianCalendar(2020, 9, 5, 5, 5), "M", true, null);
OMEGALUL

2020-09-27 06:27 UTC, Timothy-Toombs commented on AnimalTracker/app/src/main/java/toombs/animaltracker/animals/AnimalUtil.java
> +    public static String createFileName(Animal animal) {
The fileName for the animal should just be its hash.

2020-09-27 06:27 UTC, Timothy-Toombs commented on AnimalTracker/app/src/main/java/toombs/animaltracker/animals/AnimalUtil.java
> +    public static byte[] ObjectToByteArray(Object obj){
this method should only be used in this file, private.

2020-09-27 06:27 UTC, Timothy-Toombs commented on AnimalTracker/app/src/main/java/toombs/animaltracker/animals/AnimalUtil.java
> +                hashtext = "0" + hashtext;
:) this should be done with strbuffer or something else.

2020-09-27 06:27 UTC, Timothy-Toombs commented on AnimalTracker/app/src/main/java/toombs/animaltracker/animals/AnimalUtil.java
> +    public static String hashObject(byte[] byteArray){
this should probably also be made private. There should be a method "serializeAnimal" that calls serialize object, but performs some extra steps that serialize object doesn't perform (generates hash if not already present, checks that hash is present in set, puts in set if not and reserializes set, then serializes itself).

2020-09-27 06:27 UTC, Timothy-Toombs commented on AnimalTracker/app/src/main/java/toombs/animaltracker/animals/AnimalUtil.java
> +    public static Animal deserializeAnimal(Context context, String fileName){
DRY

2020-09-27 06:27 UTC, Timothy-Toombs commented on AnimalTracker/app/src/main/java/toombs/animaltracker/animals/AnimalUtil.java
> +    public static HashSet<String> deserializeAnimalSet(Context context){
DRY

2020-09-27 06:27 UTC, Timothy-Toombs commented on AnimalTracker/app/src/main/java/toombs/animaltracker/animals/AnimalUtil.java
> +    public static void serializeObject(Context context, Object obj, String fileName){
One of two strategies can be adopted here:
1. make this method private and have  serializeSet and serializeAnimal methods that call this by proxy
2. make this method public but only call it in other classes when serializing the set. (making serializeAnimal function is necessary, see below).

2020-11-10 04:34 UTC, chrissclipei commented on AnimalTracker/app/src/main/java/toombs/animaltracker/animals/AnimalUtil.java
> +    public static Animal deserializeAnimal(Context context, String fileName){
WET

2020-11-10 04:34 UTC, chrissclipei commented on AnimalTracker/app/src/main/java/toombs/animaltracker/animals/AnimalUtil.java
> +    public static HashSet<String> deserializeAnimalSet(Context context){
WET

2020-11-10 04:35 UTC, chrissclipei reviewed
Don't listen to Tim Kaho he's just a big bully YOU GOT THIS!!! SHOW HIM HOW TO CODE!!!

2020-12-11 14:27 UTC, closed without merging